### ISSUE TITLE
How to connect to eye door/window?

### ISSUE THREAD

**Issue by Binog** [ezzizzle/homebridge-garage-door-switch#2]
Hey there !

I do have the same problem You had. So I mounted an eve door/window sensor to my garage door.

But now, how to I connect the sensor with the actor. I always see a "open" badge. I do have the problem, that both the opening and the closing scripts are the same. 

Can You do a quick wiki on how to add get this done?
Thank You so much in advance !
Jimmy

**Comment by ezzizzle** [comment]
Hi Jimmy. I’ve added this [wiki page](https://github.com/ezzizzle/homebridge-garage-door-switch/wiki/Eve-Door-Sensor) with how I’m using this plugin and the Eve sensor. Does that help you get it set up?

**Comment by ezzizzle** [comment]
I'll close this for now but let me know @Binog if you need any extra help.
